ActiveStorage::Blob.create!([
  {key: "z1jxnmhxgy10cmh50gm4lncab6l0", filename: "onsen.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>5472, "height"=>3648, "analyzed"=>true}, service_name: "amazon", byte_size: 17656096, checksum: "X+DIQvvw0D3yA0Lzv33jgg=="},
  {key: "3x0jgvt6ub65o53sbc8yzss4cmwk", filename: "onsen.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>533, "analyzed"=>true}, service_name: "amazon", byte_size: 590141, checksum: "j0PoWGszZ0Kqlzuycz7fmw=="},
  {key: "jg3yyiprzxdjjscgkrpa1dxfxua1", filename: "onsen.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>333, "analyzed"=>true}, service_name: "amazon", byte_size: 256012, checksum: "IyjboIoHND6e7TmHkytCnQ=="},
  {key: "f9n1sfi8ns36xu53quq2wbi73839", filename: "onsen.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 33476, checksum: "uO6RwQTto+5jnZKq06e8PQ=="},
  {key: "c05smwixm4moapsgfawiqyk3hqw3", filename: "simanami.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>7008, "height"=>4672, "analyzed"=>true}, service_name: "amazon", byte_size: 1387683, checksum: "TsiIzqNiiN8E3+gC/kDiEg=="},
  {key: "in4kpgha0qf7ckpcmpdu28k250kf", filename: "simanami.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>533, "analyzed"=>true}, service_name: "amazon", byte_size: 147196, checksum: "1TbR6L1or0/VtVAM2tr9qw=="},
  {key: "4ye2ef0ma97yyxifz7erf4hl4x8f", filename: "simanami.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>333, "analyzed"=>true}, service_name: "amazon", byte_size: 60954, checksum: "LmmiFWu1bQ9h0g4dZJMl7Q=="},
  {key: "kcnhx7cvby3stuu5vk1dxyohs65l", filename: "simanami.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 6923, checksum: "m4BEDgp+AkSZ0jfRN5wKPA=="},
  {key: "cifs66qoqejmog6aqsjrr1xpyn2p", filename: "niihama.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>4928, "height"=>3264, "analyzed"=>true}, service_name: "amazon", byte_size: 6728906, checksum: "N+KoMXvB6maL8O1/aaOtwg=="},
  {key: "m61ybm3hcz2cnj02ueslmw13izpi", filename: "niihama.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>530, "analyzed"=>true}, service_name: "amazon", byte_size: 248937, checksum: "RrPrnXDHNqY3lK38rEIMWg=="},
  {key: "83al9gqv6umg615yv2qyj45h8511", filename: "niihama.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>331, "analyzed"=>true}, service_name: "amazon", byte_size: 101947, checksum: "Nz3uRzpyVeXbDG5WlaaEFw=="},
  {key: "7bqf0vzku3fxas6mwfol5vhx68ss", filename: "niihama.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>99, "analyzed"=>true}, service_name: "amazon", byte_size: 14505, checksum: "oKusfw1LZbl8WVU0rHdtbA=="},
  {key: "171948p5qk5xoi5h0jercp28bx9o", filename: "isiduti.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>5464, "height"=>3640, "analyzed"=>true}, service_name: "amazon", byte_size: 20678490, checksum: "qAr8yE/NGzmZ4HioVRicGw=="},
  {key: "wm0d5nb914o9pxzr8j4cv3nid8lf", filename: "isiduti.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>533, "analyzed"=>true}, service_name: "amazon", byte_size: 575644, checksum: "Um2vj+DzDZx8pKebq+I9vg=="},
  {key: "9g056c0q9oppd5ks2j7x2j4zjy1h", filename: "isiduti.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 28253, checksum: "lRy/JHW01dLi1HxiYkeRDQ=="},
  {key: "02qdo0pk8ibqdtr7bxxulozh41si", filename: "isiduti.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>333, "analyzed"=>true}, service_name: "amazon", byte_size: 235678, checksum: "Z+zhNsuzC/TU0+3pAd+cqg=="},
  {key: "3cg5kuflp9pziico0a3n9c13erqp", filename: "aosima.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>4896, "height"=>3264, "analyzed"=>true}, service_name: "amazon", byte_size: 10311559, checksum: "bUufaTlhr54C3dZrtlXutA=="},
  {key: "2c1i0nlqreon98hkdxb1snroc4o6", filename: "aosima.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>533, "analyzed"=>true}, service_name: "amazon", byte_size: 497675, checksum: "aM5pslNzxEMQMLyxt70w5g=="},
  {key: "wiwkvp08qp0ooqdq30hl2jwv7pif", filename: "aosima.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 29334, checksum: "SZzk2Q8qvIzLnUr1aA/Keg=="},
  {key: "kpf3u0n1yp2vydfotmbcefuoi9z2", filename: "iyosi.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>5184, "height"=>3456, "analyzed"=>true}, service_name: "amazon", byte_size: 16976079, checksum: "9temIdjT8H83kpRGb+fMbg=="},
  {key: "l29knpv14jsm67pihx0py7cpga8v", filename: "iyosi.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>533, "analyzed"=>true}, service_name: "amazon", byte_size: 636439, checksum: "RntBJrAgjqvh1zATRpmNEg=="},
  {key: "pkwhjlbmqso0czotr3xq9a686u6s", filename: "iyosi.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 33933, checksum: "FzI3IJeyONWd/4izRqvJtQ=="},
  {key: "w59mzexgnoznnmjj0awytxgm20gs", filename: "utiko.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>4912, "height"=>3264, "analyzed"=>true}, service_name: "amazon", byte_size: 14802586, checksum: "dnUMkhC7x8rL8RiydVGXEQ=="},
  {key: "nir3uo5fuxrrd6ualctocatbivyo", filename: "utiko.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>532, "analyzed"=>true}, service_name: "amazon", byte_size: 369525, checksum: "IpTCuW/tgE+NLBapsxLOpw=="},
  {key: "9cqq2zj3c4dcvexcnn0s6pqlitok", filename: "aosima.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>333, "analyzed"=>true}, service_name: "amazon", byte_size: 221477, checksum: "N9OBMociKEYDxovr74QVQQ=="},
  {key: "65y7jsy1syhmumtvxhtc3hakc9mn", filename: "iyosi.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>333, "analyzed"=>true}, service_name: "amazon", byte_size: 265969, checksum: "2o/AQMBqmRUjvpT6YC+skg=="},
  {key: "jqn7u4xkgcnt4tzn87et6sj9tibp", filename: "utiko.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>332, "analyzed"=>true}, service_name: "amazon", byte_size: 152904, checksum: "IlXh3i2pLH27deduMUpvMw=="},
  {key: "9eyel16id959hcj7l4chbogpwhke", filename: "utiko.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 21133, checksum: "kINUx0whzMwV3diIg/nusw=="},
  {key: "xqzw2zql3zhhaksrru0rq722mbjv", filename: "misaki.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>9601, "height"=>5863, "analyzed"=>true}, service_name: "amazon", byte_size: 39684993, checksum: "CVlIcMnUSp36YjyIg0ZIJQ=="},
  {key: "bauwbifmt1vivuqiwei4en52ap1d", filename: "misaki.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>489, "analyzed"=>true}, service_name: "amazon", byte_size: 302779, checksum: "58mwnk/TIUtSfu6wvVFy5w=="},
  {key: "nxutaq9itcdqfffe60yh2v8xi7ml", filename: "misaki.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>92, "analyzed"=>true}, service_name: "amazon", byte_size: 17793, checksum: "cpsAnyG3wKmBHK+0wh59vQ=="},
  {key: "prl56d6oftwdog0cph332hv97mmo", filename: "misaki.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>305, "analyzed"=>true}, service_name: "amazon", byte_size: 125023, checksum: "Zcv9pkg0QyTBmww1rn52lA=="},
  {key: "1owdpkgn93pfuxbyamcsk0ieoktx", filename: "climbing-forest-906973_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>1280, "height"=>853, "analyzed"=>true}, service_name: "amazon", byte_size: 61199, checksum: "2IgsLLZF00ajdTOB2EGq5A=="},
  {key: "jkzxna9gb8v30lslwek6dp2hhew3", filename: "climbing-forest-906973_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>533, "analyzed"=>true}, service_name: "amazon", byte_size: 122645, checksum: "Vo0toyxjCpKXV9en923rNQ=="},
  {key: "5bhxzivaqr2vf7xyhf1759pql7a7", filename: "climbing-forest-906973_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 9328, checksum: "XzNFfnEZoCRXkzT6r48L4w=="},
  {key: "idhmzeeirx6lsz59vr9rf4ebf937", filename: "hot-air-balloons-5390487_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>1280, "height"=>861, "analyzed"=>true}, service_name: "amazon", byte_size: 25661, checksum: "GpH1gHBXwCeJGXSCMkUpmQ=="},
  {key: "bnb3096pd90r61h15qml6xx6hshu", filename: "hot-air-balloons-5390487_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>538, "analyzed"=>true}, service_name: "amazon", byte_size: 52292, checksum: "ISwnttlomgpcl22TRYOHHg=="},
  {key: "zkib13kx495qes9jwutz7en8nvv9", filename: "hot-air-balloons-5390487_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>101, "analyzed"=>true}, service_name: "amazon", byte_size: 4618, checksum: "1bg7LoVxNhueTv7kqq0Fzw=="},
  {key: "phokn4q9d4ixx95dy0ggjgoc04yu", filename: "zip-line-7608200_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>1280, "height"=>853, "analyzed"=>true}, service_name: "amazon", byte_size: 68195, checksum: "OV3rSArTpnuuEZ0ygYXWCg=="},
  {key: "by6edk0gfo9754iwa76i780d388j", filename: "zip-line-7608200_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>533, "analyzed"=>true}, service_name: "amazon", byte_size: 125800, checksum: "Mn8vOicsqEmwu278cKqXrw=="},
  {key: "mn2bqxxndrrdhsywjt3fu7fy54ry", filename: "zip-line-7608200_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 6482, checksum: "/3c9/TWD1kCYk0DNOhhK1Q=="},
  {key: "y9q10ejhbxauzlpt94ma6rlsls2d", filename: "salt-of-joy-1117720_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>1280, "height"=>960, "analyzed"=>true}, service_name: "amazon", byte_size: 105254, checksum: "oeu8C+mqLIcDFwMACMZ0IA=="},
  {key: "d5xa867r3x544ksh9teicobjefin", filename: "salt-of-joy-1117720_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>600, "analyzed"=>true}, service_name: "amazon", byte_size: 191366, checksum: "OURN2zL3nn0Hi6xMtwvA8A=="},
  {key: "r3klms5168z7dfza5i07b7h4hffi", filename: "salt-of-joy-1117720_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>113, "analyzed"=>true}, service_name: "amazon", byte_size: 8466, checksum: "80gPyqBLHuuH+V9fY225AQ=="},
  {key: "u4rc2zyuislr3nlwknn0k7m3tedq", filename: "spain-7341871_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>1280, "height"=>848, "analyzed"=>true}, service_name: "amazon", byte_size: 99608, checksum: "okVl1p2Xc81FdUnaywWU3Q=="},
  {key: "2kzfmtr2os9i5r9aiipafkufxu6a", filename: "spain-7341871_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>530, "analyzed"=>true}, service_name: "amazon", byte_size: 164802, checksum: "Llwz/JXF7gsXkNyZG4gDPg=="},
  {key: "cnuwo8ssb52r8pjs5ak7zdrgjh3q", filename: "spain-7341871_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>99, "analyzed"=>true}, service_name: "amazon", byte_size: 7192, checksum: "J5SNRzI0ps4FkDdGnYZz0A=="},
  {key: "igb6z1wx83q7ak4xj96gua8hgfck", filename: "japan-1040658_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>1280, "height"=>960, "analyzed"=>true}, service_name: "amazon", byte_size: 102724, checksum: "e2QxdNMob9pviuLndtCVOA=="},
  {key: "wifar5xld6vjij5z4ghtklzlk2w3", filename: "japan-1040658_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>600, "analyzed"=>true}, service_name: "amazon", byte_size: 182674, checksum: "m1FR3DRGumA5+QrxeEkytQ=="},
  {key: "eytp0dqz36u4utz2iadvkrrz7810", filename: "japan-1040658_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>113, "analyzed"=>true}, service_name: "amazon", byte_size: 9103, checksum: "vM2q513lK3YAr8u3H1xHvw=="},
  {key: "modqpzzilnb06n5czeb8ssxiuhxi", filename: "sea-3741909_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>1280, "height"=>853, "analyzed"=>true}, service_name: "amazon", byte_size: 20436, checksum: "bsSM+b3E7MFhuo6lfx4P0Q=="},
  {key: "vfl9295atwkddfizgec66zib0i6o", filename: "sea-3741909_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>533, "analyzed"=>true}, service_name: "amazon", byte_size: 57646, checksum: "Kj54vFJYizlXyKxdPIj9Ug=="},
  {key: "adfg290nlj54izicg1ygm7y51rtm", filename: "sea-3741909_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 3661, checksum: "ofXpBZgtMjXghNToO2Twcw=="},
  {key: "yiqi5yfi6sgiooq176vnsv6wc1io", filename: "tea.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>1280, "height"=>853, "analyzed"=>true}, service_name: "amazon", byte_size: 22795, checksum: "nTw5MmuUE5ECtA8FyluSeQ=="},
  {key: "haja6nlw3jjj7upboiuwshgn0x9q", filename: "tea.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>533, "analyzed"=>true}, service_name: "amazon", byte_size: 52061, checksum: "26x1GMIkwFu9Kf4e+kYtiA=="},
  {key: "oztum6yeooveoulibdiaot7pskke", filename: "tea.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 4890, checksum: "PnhZ0fQ+yn26p233L4lh5g=="},
  {key: "ly49aeetkxo9g7ju82rk5es0rrw9", filename: "somen-6566678_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>1280, "height"=>853, "analyzed"=>true}, service_name: "amazon", byte_size: 69453, checksum: "so2seceYouHZiOouq0qQIw=="},
  {key: "8ou2ws6ahdg0qk2meljf209i9rcf", filename: "somen-6566678_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>533, "analyzed"=>true}, service_name: "amazon", byte_size: 132487, checksum: "vED1VT/bBslSW79CtGlE4Q=="},
  {key: "oy4dsqt6vn7yn7b9uoecs3q9p16v", filename: "somen-6566678_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 7671, checksum: "s4S74DcFWb3qGGuEu/3cGg=="},
  {key: "wb0b0zzzx6ii4siw8x1rzkip4121", filename: "fish-7581019_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>1280, "height"=>768, "analyzed"=>true}, service_name: "amazon", byte_size: 72921, checksum: "jkg9vnpS35ABcLhYJIFSjA=="},
  {key: "txvqxlsn0eg3phbceqzridoao5ao", filename: "fish-7581019_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>480, "analyzed"=>true}, service_name: "amazon", byte_size: 130136, checksum: "YJeACMmB5z8UC4KfEeYHug=="},
  {key: "drgool1uxp3yss3vs1u1zhyrp6jr", filename: "fish-7581019_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>90, "analyzed"=>true}, service_name: "amazon", byte_size: 7198, checksum: "IY7lBNg8G4leUYLXQVO9dg=="},
  {key: "3v5d5uuzqz6dlfm92sohwk3mqiib", filename: "antwerp-7623081_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>1280, "height"=>853, "analyzed"=>true}, service_name: "amazon", byte_size: 50913, checksum: "XJPt5MK+RD7UAE5TNMJt7w=="},
  {key: "akwlaizmb7qygzbwowjjhytusc5g", filename: "antwerp-7623081_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>533, "analyzed"=>true}, service_name: "amazon", byte_size: 100598, checksum: "6dp8+Ze5ifh3llgh7h03rQ=="},
  {key: "5crgve5xeae2gntpy4fh9c3lkqji", filename: "antwerp-7623081_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 6567, checksum: "TiKbmCKnroYSBUrCOta92Q=="},
  {key: "jpr3ck3df9ztmn461875l6u8ylgv", filename: "spring.png", content_type: "image/png", metadata: {"identified"=>true, "width"=>2048, "height"=>1536, "analyzed"=>true}, service_name: "amazon", byte_size: 789822, checksum: "bOI2wBe4L4SIolOTD0PTrA=="},
  {key: "eyfk5sd5hb4vwy4vjxtzkov46wvt", filename: "spring.png", content_type: "image/png", metadata: {"identified"=>true, "width"=>800, "height"=>600, "analyzed"=>true}, service_name: "amazon", byte_size: 704066, checksum: "y5zQmyTMjeq83d5gUwldWQ=="},
  {key: "8yjeu2icacxkf05z0yqlz8sdoc9j", filename: "shutterstock_1861457032.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>2048, "height"=>1536, "analyzed"=>true}, service_name: "amazon", byte_size: 302691, checksum: "cseb4voX7XPqdO/hpwHitA=="},
  {key: "s4h880pmujg7ix2p0t98ae9wj72w", filename: "shutterstock_1861457032.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>600, "analyzed"=>true}, service_name: "amazon", byte_size: 237242, checksum: "mY7CDWhYAbVS7q58KunxRA=="},
  {key: "5e0wa4yfxxb54qcca1a1nnv89cpo", filename: "shutterstock_1549869161.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>2048, "height"=>1365, "analyzed"=>true}, service_name: "amazon", byte_size: 212641, checksum: "tUkXXJFT7c/a4JeeK6uXwQ=="},
  {key: "nfjz4i494l5nluwwxmlzb9vliqev", filename: "shutterstock_1549869161.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>533, "analyzed"=>true}, service_name: "amazon", byte_size: 174918, checksum: "Nui67UZjH+dpXLZzUrUuUw=="},
  {key: "09a6y8xleh7v49unjidyxrui180j", filename: "japan-960260_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>1280, "height"=>960, "analyzed"=>true}, service_name: "amazon", byte_size: 67066, checksum: "pD/F2sfoLljet4pE+PgcxQ=="},
  {key: "s28382gezqryhfcz1iie7r13tuzl", filename: "japan-960260_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>600, "analyzed"=>true}, service_name: "amazon", byte_size: 126801, checksum: "V0BuHLX15YbBoyn0w/UD+Q=="},
  {key: "8mgreu7tbc0uocjln1evvjyzg34f", filename: "shutterstock_1959414952.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>2047, "height"=>1395, "analyzed"=>true}, service_name: "amazon", byte_size: 135089, checksum: "Eo2ry4DTXssatJ+K2jV8qA=="},
  {key: "bnvrmeeuvb698qj5snr5v0sf3xrb", filename: "shutterstock_1959414952.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>545, "analyzed"=>true}, service_name: "amazon", byte_size: 134807, checksum: "ZaW1p+YLQvFhclxp+r1L7A=="},
  {key: "xdeckwfn4i8vkk2f4l4g1zjzfrz5", filename: "japan-75770_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>1280, "height"=>960, "analyzed"=>true}, service_name: "amazon", byte_size: 98440, checksum: "X0H2zbWBvWDzPJsk3a9wLQ=="},
  {key: "kmw3wc5um2hyd9rzbbqud2zcxpc4", filename: "japan-75770_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>600, "analyzed"=>true}, service_name: "amazon", byte_size: 163426, checksum: "njbUFnf/dFOyu0qT14M7/g=="},
  {key: "hyr7h7bnqjw941xms1sfoyvpm4q6", filename: "taoru.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>1280, "height"=>1280, "analyzed"=>true}, service_name: "amazon", byte_size: 46484, checksum: "05gfAOtNJnzAEwwUKOi+5A=="},
  {key: "e3abzp3zzxgfl6mzgbw6ssr4lamp", filename: "taoru.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>800, "analyzed"=>true}, service_name: "amazon", byte_size: 110150, checksum: "D3c1I9wCRBblzDKG81YZig=="},
  {key: "xzwfy3ot52pkofqr65efqcilzx76", filename: "orange-1921548_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>1280, "height"=>853, "analyzed"=>true}, service_name: "amazon", byte_size: 35330, checksum: "Z4cpmLKmZP2BQ8kdg4iUpw=="},
  {key: "ub466rvbzuoq8cylfm0vuciyuiau", filename: "orange-1921548_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>533, "analyzed"=>true}, service_name: "amazon", byte_size: 74560, checksum: "rlkJeXKKBHZFr5YsLN1gYg=="},
  {key: "9cye0fzsp7wyixa8o6cgv9oi4yar", filename: "pottery-1139047_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>1280, "height"=>914, "analyzed"=>true}, service_name: "amazon", byte_size: 59152, checksum: "ZUHE5Zyp1fVKz8FVWJNg5A=="},
  {key: "bmpif74pvg8ulaqufbp2ow7vgjlr", filename: "pottery-1139047_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>800, "height"=>571, "analyzed"=>true}, service_name: "amazon", byte_size: 122277, checksum: "+bUc14qo+Zs5KPnh0lG59g=="},
  {key: "w3iwndkwhfd09h4q9wapv5sqsrdx", filename: "climbing-forest-906973_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>333, "analyzed"=>true}, service_name: "amazon", byte_size: 61747, checksum: "Il2TOc53hKqFDz/tFCOjMg=="},
  {key: "vypjg131erio8oxdthp210cp2vue", filename: "zip-line-7608200_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>333, "analyzed"=>true}, service_name: "amazon", byte_size: 55745, checksum: "ss1uRpxGVFkNSh6RfJPd4Q=="},
  {key: "8eeipu6t9hvfeglncus6viqwx5fa", filename: "hot-air-balloons-5390487_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>336, "analyzed"=>true}, service_name: "amazon", byte_size: 26357, checksum: "SeizhOUO0omghE1ko3/b3w=="},
  {key: "m8qomtd69mw7bdd39f6ycl5tr3hb", filename: "salt-of-joy-1117720_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>375, "analyzed"=>true}, service_name: "amazon", byte_size: 80575, checksum: "8LtI6OwkB05rxtGBtCSV6w=="},
  {key: "a5brvi8b6od6oz2yk1z25s0d4ug1", filename: "japan-1040658_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>375, "analyzed"=>true}, service_name: "amazon", byte_size: 79539, checksum: "k4D6o5+lCKVWwKHejn/X7g=="},
  {key: "9nzg4zaqvk0u1zv9bs0mv9wtdla7", filename: "sea-3741909_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>333, "analyzed"=>true}, service_name: "amazon", byte_size: 27127, checksum: "s3WW4bq9vvtbubkSnYEIcQ=="},
  {key: "ppaen4uxs9mity71qtnd5be7mec2", filename: "shutterstock_1549869161.jpg", content_type: "image/jpeg", metadata: {"identified"=>true}, service_name: "amazon", byte_size: 74641, checksum: "bmQm3zotzfBY2L8q5ISngQ=="},
  {key: "dudslbxu5d4vlxba4w57uax36uxj", filename: "antwerp-7623081_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>333, "analyzed"=>true}, service_name: "amazon", byte_size: 47373, checksum: "qRfzfa6zS8gFYOXw04IbvA=="},
  {key: "siyrurn1pk21mngb3kqgclfpbzhp", filename: "spring.png", content_type: "image/png", metadata: {"identified"=>true, "width"=>500, "height"=>375, "analyzed"=>true}, service_name: "amazon", byte_size: 283547, checksum: "vxftiNsC8sV/N7VV9BcqFA=="},
  {key: "9tyve4ben97uv0dspjnpzyx8yhgs", filename: "shutterstock_1861457032.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>375, "analyzed"=>true}, service_name: "amazon", byte_size: 98393, checksum: "pUbtyWgOrRn7r+V/sKqSsA=="},
  {key: "ipcrfvm8k4x2t43177tjfubozoev", filename: "taoru.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>500, "analyzed"=>true}, service_name: "amazon", byte_size: 50994, checksum: "myclBuNh7Q06m5BlGhOS6A=="},
  {key: "hku4wfmr9qsinld17fsioyycytr7", filename: "shutterstock_1959414952.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>341, "analyzed"=>true}, service_name: "amazon", byte_size: 58882, checksum: "PjiuH9lE59rSNvykXBFkSw=="},
  {key: "fjzthqyrn5dc0ggox9c7wqxu1wop", filename: "somen-6566678_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>333, "analyzed"=>true}, service_name: "amazon", byte_size: 62068, checksum: "wUXr9bntDHR2sdv0TgYkZg=="},
  {key: "ixecklneupmz29ymkv6kgoxnluab", filename: "fish-7581019_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>300, "analyzed"=>true}, service_name: "amazon", byte_size: 57506, checksum: "EOACbVfx73lmPakgwuMNtQ=="},
  {key: "g9ko6qse10bpd02uvjynbulatvlv", filename: "tea.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>333, "analyzed"=>true}, service_name: "amazon", byte_size: 26442, checksum: "xjg9wkovpVB5apfPlh+eLA=="},
  {key: "a7afb9mgair1h8boco3sqx95zt38", filename: "spain-7341871_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>331, "analyzed"=>true}, service_name: "amazon", byte_size: 68011, checksum: "yCdz2G3p7x+NI2GBAc/w3A=="},
  {key: "v0xho14uzyior0qyuktn7ri5urfz", filename: "pottery-1139047_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>357, "analyzed"=>true}, service_name: "amazon", byte_size: 56495, checksum: "8rtIviAJeMXI7M3mwiNEHg=="},
  {key: "oa378bx5f4h5m33jttv1tieng01q", filename: "orange-1921548_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>333, "analyzed"=>true}, service_name: "amazon", byte_size: 35732, checksum: "TZsNI1E8n0KShDkXvwfuEQ=="},
  {key: "jh7gxcmlkfvo9ophe3xn8415e7oc", filename: "japan-960260_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true}, service_name: "amazon", byte_size: 8357, checksum: "rHmnmxu75VX6Ii+tmBp2Ww=="},
  {key: "9hatux3rb8iplp6x3wqlmp5rvmcp", filename: "shutterstock_1959414952.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>102, "analyzed"=>true}, service_name: "amazon", byte_size: 6908, checksum: "fEFDtd82PApRY36yTtOcQw=="},
  {key: "7ul5cp5f33l4anfhpznoe1s68rw1", filename: "shutterstock_1549869161.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 8198, checksum: "vD8ga2vW0k64tABcBEvGpQ=="},
  {key: "iv06fcd1c7po6etjgpi7e9oal5qw", filename: "taoru.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>150, "analyzed"=>true}, service_name: "amazon", byte_size: 6216, checksum: "+OaLKHBJH5iCw8VAw5upwg=="},
  {key: "5hngapxhj91hukhjhy5wg0gq201v", filename: "orange-1921548_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 5873, checksum: "ScQPvrLe/O3v2lI3KQ7cmA=="},
  {key: "c50imwesks6pvgmk7v5ipowakr4f", filename: "pottery-1139047_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>107, "analyzed"=>true}, service_name: "amazon", byte_size: 7765, checksum: "2tXsXte193VjP7RNODsk/g=="},
  {key: "k5uh79q41fbshib1mck74vfsuybk", filename: "japan-75770_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>113, "analyzed"=>true}, service_name: "amazon", byte_size: 7778, checksum: "MQEJw3WbUA7f+5Oh5FHUdQ=="},
  {key: "i646ecag067zcewsi11iaa9d1ndm", filename: "shutterstock_1861457032.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>113, "analyzed"=>true}, service_name: "amazon", byte_size: 9807, checksum: "WlFr3YPeh8ofvS+YUBJtgQ=="},
  {key: "h6v0fh7gectk1xxcj2fi7xa07hol", filename: "spring.png", content_type: "image/png", metadata: {"identified"=>true, "width"=>150, "height"=>113, "analyzed"=>true}, service_name: "amazon", byte_size: 30311, checksum: "ZugerVOKOr6xhi3snwPKbw=="},
  {key: "hn9c710u9kncm519bt2m4s1k6adt", filename: "japan-75770_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>375, "analyzed"=>true}, service_name: "amazon", byte_size: 68923, checksum: "GtQ/inyA9S56U5gYBsrv4w=="},
  {key: "qtli8u785lvjet056m1fmz9jis8p", filename: "japan-960260_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>375, "analyzed"=>true}, service_name: "amazon", byte_size: 59587, checksum: "jxtgjUiljiE3oHpU03QNfw=="},
  {key: "eurcay3fxz2jyjlb7l0ou8vylg3i", filename: "japan-75770_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>500, "height"=>375, "analyzed"=>true}, service_name: "amazon", byte_size: 68923, checksum: "GtQ/inyA9S56U5gYBsrv4w=="},
  {key: "f3uwf8f9z0ka191eizwsexgmber3", filename: "japan-75770_1280.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>113, "analyzed"=>true}, service_name: "amazon", byte_size: 7778, checksum: "MQEJw3WbUA7f+5Oh5FHUdQ=="},
  {key: "xwmjfrvz92m9j9sjjygcnd7sv3s8", filename: "spring.png", content_type: "image/png", metadata: {"identified"=>true, "width"=>667, "height"=>500, "analyzed"=>true}, service_name: "amazon", byte_size: 493763, checksum: "Rr+8zA8OHV4IX17yX3SENg=="},
  {key: "575zex6r99k1o2oaok3nozean9rq", filename: "spring.png", content_type: "image/png", metadata: {"identified"=>true, "width"=>667, "height"=>500, "analyzed"=>true}, service_name: "amazon", byte_size: 493776, checksum: "oW7aU/nIBpmHfvoeYKyqmQ=="},
  {key: "c4h59wvls51wpio1m83hx323ks4z", filename: "spring.png", content_type: "image/png", metadata: {"identified"=>true, "width"=>150, "height"=>112, "analyzed"=>true}, service_name: "amazon", byte_size: 32130, checksum: "kuFwnAmeE5ITuNZEr91x7A=="},
  {key: "y5n3dxnvdkrzb256546ikub78liu", filename: "23432.jpeg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>700, "height"=>467, "analyzed"=>true}, service_name: "amazon", byte_size: 262595, checksum: "IFQ0sBJmS1fG0AirNCbCig=="},
  {key: "8uuioj754nzwmu0nl3ow3nt7hkua", filename: "23432.jpeg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>700, "height"=>467, "analyzed"=>true}, service_name: "amazon", byte_size: 261423, checksum: "vY/Fm644Go+40baB3F1cBQ=="},
  {key: "u8x086mau8gwtax03ak8az21e2c1", filename: "23432.jpeg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 80880, checksum: "3HnvRhOgRlpHYMbLexcKkQ=="},
  {key: "06wckbjd0y6um97gmetdkrd38rw2", filename: "1307764_m.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>700, "height"=>468, "analyzed"=>true}, service_name: "amazon", byte_size: 296754, checksum: "8rWeenUTsFwTWKObkhPoUQ=="},
  {key: "awuvsu0nfh1gf1q24ggosx8orbnz", filename: "1307764_m.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>700, "height"=>468, "analyzed"=>true}, service_name: "amazon", byte_size: 287755, checksum: "Auo9RAOGaP7Q3fclAUa11w=="},
  {key: "nutsbm3jdraz8r395pxro64dpu1w", filename: "1307764_m.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 15292, checksum: "hRlXPFycAlHXkvjk2Upeyg=="},
  {key: "scuhhb6r5p5evw3rhzfd4138ajtl", filename: "summer.png", content_type: "image/png", metadata: {"identified"=>true, "width"=>667, "height"=>500, "analyzed"=>true}, service_name: "amazon", byte_size: 568120, checksum: "pTAAbtEG7PRAzcisnJeXNw=="},
  {key: "dwt0a1lk5jlz49eq0dh18nzlm9x3", filename: "summer.png", content_type: "image/png", metadata: {"identified"=>true, "width"=>667, "height"=>500, "analyzed"=>true}, service_name: "amazon", byte_size: 568133, checksum: "C3FvhhdosVTu9i7Ss8azBg=="},
  {key: "794k5yjcydqc3xcebbhvpphd60os", filename: "summer.png", content_type: "image/png", metadata: {"identified"=>true, "width"=>150, "height"=>112, "analyzed"=>true}, service_name: "amazon", byte_size: 31232, checksum: "KoNRinJwHH7ThN7PaGu9vQ=="},
  {key: "11q1e52g43tbxnb3bkrhw41ibego", filename: "24653750_m.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>700, "height"=>466, "analyzed"=>true}, service_name: "amazon", byte_size: 115413, checksum: "wmCbvb049zOHGfiG8B8A0A=="},
  {key: "rxuz9stgwcvfywpswloadlb452j1", filename: "24653750_m.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>700, "height"=>466, "analyzed"=>true}, service_name: "amazon", byte_size: 115218, checksum: "uJnkieb/VqL7Nw17SPVnqg=="},
  {key: "lw0qia6kuwnd8038ykb4o10bfah6", filename: "24653750_m.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 8743, checksum: "V6uxRaMsM7xYhKpjhHaNvg=="},
  {key: "8njwgekfamxp5in5lnmq55j2pikp", filename: "24173922_m.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>700, "height"=>468, "analyzed"=>true}, service_name: "amazon", byte_size: 63833, checksum: "FZHht1AgraQCcNaV75VTDQ=="},
  {key: "chmb1ofoi3sm4002etdbpzp8awca", filename: "24173922_m.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>700, "height"=>468, "analyzed"=>true}, service_name: "amazon", byte_size: 63298, checksum: "YaSBrzMeqDF/FBPHbNrWcg=="},
  {key: "mwhe3a7rx6w0o55tp3hlkw2e9ta1", filename: "24173922_m.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 4471, checksum: "vEhnbBJkIXW12ZSMhfWAqQ=="},
  {key: "y2cw3itf3pi5po8oyou7ojh2dp2b", filename: "autumn.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>665, "height"=>500, "analyzed"=>true}, service_name: "amazon", byte_size: 103882, checksum: "tpRgBKBkukQkN3k1l5uMEw=="},
  {key: "xjmqd4s8aggqx1mh9kosiou7qcay", filename: "autumn.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>665, "height"=>500, "analyzed"=>true}, service_name: "amazon", byte_size: 103706, checksum: "TvRVOmOOzEYshc6DHQHtRA=="},
  {key: "sdft338e8xqcjn0x6tivmze32a4v", filename: "autumn.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>113, "analyzed"=>true}, service_name: "amazon", byte_size: 8391, checksum: "8PS8S5matzTUvcXD4L5u6A=="},
  {key: "8d69k5cid0kn71bmu9zeq1oxgvn1", filename: "onsen.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>700, "height"=>467, "analyzed"=>true}, service_name: "amazon", byte_size: 468705, checksum: "4c5rXei8CI9pyY5fdMtVKg=="},
  {key: "pw5ns5cd18g4rx7fa74kwjab1bb7", filename: "onsen.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>700, "height"=>467, "analyzed"=>true}, service_name: "amazon", byte_size: 474276, checksum: "9mV4Telua+QVvL91OqmPJw=="},
  {key: "2uyxvnh2y110r6w800ekc96wkep9", filename: "onsen.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 33512, checksum: "R9zwVSmuZntI7tn0dW04cw=="},
  {key: "6c3ujkla5hqkne47daepqej1nczb", filename: "1143530_m (1).jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>700, "height"=>468, "analyzed"=>true}, service_name: "amazon", byte_size: 121883, checksum: "w2oKoV+aoS9+Z/NTD5s48Q=="},
  {key: "38zc70qfjzn3l4z77ghl9lrc791e", filename: "1143530_m (1).jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>700, "height"=>468, "analyzed"=>true}, service_name: "amazon", byte_size: 121763, checksum: "tZH0+L6uVFdB+0wWbgr4nQ=="},
  {key: "y0651rwau32ttwfldl80yet15q7i", filename: "1143530_m (1).jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>150, "height"=>100, "analyzed"=>true}, service_name: "amazon", byte_size: 6999, checksum: "eH1MzvtQofEWj6/jiov3yA=="},
  {key: "pl09wg6ai6ou05agmll1gkbv8k5i", filename: "25930514_m.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>700, "height"=>467, "analyzed"=>true}, service_name: "amazon", byte_size: 123493, checksum: "EXgOqXKxkkKz1Gk7nP8qaw=="},
  {key: "3iuny376wapmq66fxb9n915qinm7", filename: "25930514_m.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>700, "height"=>467, "analyzed"=>true}, service_name: "amazon", byte_size: 122284, checksum: "vk/zc62fg6clSD5iwcbfBA=="}
])
ActiveStorage::VariantRecord = ([
  {blob_id: 1, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 1, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 1, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 5, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 5, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 5, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 9, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 9, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 9, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 13, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 13, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 13, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 17, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 17, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 20, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 20, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 23, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 17, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 20, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 23, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 23, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 29, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 29, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 29, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 33, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 33, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 36, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 36, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 39, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 39, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 42, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 42, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 45, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 45, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 48, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 48, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 51, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 51, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 54, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 54, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 57, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 57, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 60, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 60, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 63, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 63, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 66, variation_digest: "oVj7i/n+6fv54/e/IrAmwBJg5hA="},
  {blob_id: 68, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 70, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 72, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 74, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 76, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 78, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 80, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 82, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 33, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 39, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 36, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 42, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 48, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 51, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 70, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 63, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 66, variation_digest: "grOmaDDD+qNEEvS3BZzaB227f44="},
  {blob_id: 68, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 78, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 74, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 57, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 60, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 54, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 45, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 82, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 80, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 72, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 74, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 70, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 78, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 80, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 82, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 76, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 68, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 66, variation_digest: "G0Vst4geCVOXNaQRJ+bGaGFNhTs="},
  {blob_id: 76, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 72, variation_digest: "o6FvqsFkA8vhEYgai/NTHqoEOlQ="},
  {blob_id: 173, variation_digest: "oVj7i/n+6fv54/e/IrAmwBJg5hA="},
  {blob_id: 173, variation_digest: "G0Vst4geCVOXNaQRJ+bGaGFNhTs="},
  {blob_id: 176, variation_digest: "pyLviDWX04C+UUbhLvzku5ELF5Q="},
  {blob_id: 176, variation_digest: "7GSB7XKiQxDNPaQRLwPzuOQWE9k="},
  {blob_id: 179, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 179, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 182, variation_digest: "oVj7i/n+6fv54/e/IrAmwBJg5hA="},
  {blob_id: 182, variation_digest: "G0Vst4geCVOXNaQRJ+bGaGFNhTs="},
  {blob_id: 185, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 185, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 188, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 188, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 191, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 191, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 194, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 194, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 197, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="},
  {blob_id: 197, variation_digest: "W3rQbiDVl3RX0dJoKIDlgkZ9b4A="},
  {blob_id: 200, variation_digest: "B62VV7bY7IWpNU2HcpGzeHQxcSo="}
])
ActiveStorage::Attachment.create!([
  {name: "icon", record_type: "Spot", record_id: 1, blob_id: 1},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 1, blob_id: 2},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 2, blob_id: 3},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 3, blob_id: 4},
  {name: "icon", record_type: "Spot", record_id: 2, blob_id: 5},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 4, blob_id: 6},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 5, blob_id: 7},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 6, blob_id: 8},
  {name: "icon", record_type: "Spot", record_id: 3, blob_id: 9},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 7, blob_id: 10},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 8, blob_id: 11},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 9, blob_id: 12},
  {name: "icon", record_type: "Spot", record_id: 4, blob_id: 13},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 10, blob_id: 14},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 11, blob_id: 15},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 12, blob_id: 16},
  {name: "icon", record_type: "Spot", record_id: 5, blob_id: 17},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 13, blob_id: 18},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 14, blob_id: 19},
  {name: "icon", record_type: "Spot", record_id: 6, blob_id: 20},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 15, blob_id: 21},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 16, blob_id: 22},
  {name: "icon", record_type: "Spot", record_id: 7, blob_id: 23},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 17, blob_id: 24},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 18, blob_id: 25},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 19, blob_id: 26},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 20, blob_id: 27},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 21, blob_id: 28},
  {name: "icon", record_type: "Spot", record_id: 8, blob_id: 29},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 22, blob_id: 30},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 23, blob_id: 31},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 24, blob_id: 32},
  {name: "icon", record_type: "Spot", record_id: 9, blob_id: 33},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 25, blob_id: 34},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 26, blob_id: 35},
  {name: "icon", record_type: "Spot", record_id: 11, blob_id: 36},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 27, blob_id: 37},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 28, blob_id: 38},
  {name: "icon", record_type: "Spot", record_id: 10, blob_id: 39},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 29, blob_id: 40},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 30, blob_id: 41},
  {name: "icon", record_type: "Spot", record_id: 12, blob_id: 42},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 31, blob_id: 43},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 32, blob_id: 44},
  {name: "icon", record_type: "Spot", record_id: 13, blob_id: 45},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 33, blob_id: 46},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 34, blob_id: 47},
  {name: "icon", record_type: "Spot", record_id: 14, blob_id: 48},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 35, blob_id: 49},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 36, blob_id: 50},
  {name: "icon", record_type: "Spot", record_id: 15, blob_id: 51},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 37, blob_id: 52},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 38, blob_id: 53},
  {name: "icon", record_type: "Spot", record_id: 16, blob_id: 54},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 39, blob_id: 55},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 40, blob_id: 56},
  {name: "icon", record_type: "Spot", record_id: 17, blob_id: 57},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 41, blob_id: 58},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 42, blob_id: 59},
  {name: "icon", record_type: "Spot", record_id: 18, blob_id: 60},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 43, blob_id: 61},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 44, blob_id: 62},
  {name: "icon", record_type: "Spot", record_id: 20, blob_id: 63},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 45, blob_id: 64},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 46, blob_id: 65},
  {name: "icon", record_type: "Spot", record_id: 21, blob_id: 66},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 47, blob_id: 67},
  {name: "icon", record_type: "Spot", record_id: 22, blob_id: 68},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 48, blob_id: 69},
  {name: "icon", record_type: "Spot", record_id: 23, blob_id: 70},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 49, blob_id: 71},
  {name: "icon", record_type: "Spot", record_id: 24, blob_id: 72},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 50, blob_id: 73},
  {name: "icon", record_type: "Spot", record_id: 25, blob_id: 74},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 51, blob_id: 75},
  {name: "icon", record_type: "Spot", record_id: 26, blob_id: 76},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 52, blob_id: 77},
  {name: "icon", record_type: "Spot", record_id: 27, blob_id: 78},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 53, blob_id: 79},
  {name: "icon", record_type: "Spot", record_id: 28, blob_id: 80},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 54, blob_id: 81},
  {name: "icon", record_type: "Spot", record_id: 29, blob_id: 82},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 55, blob_id: 83},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 56, blob_id: 84},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 57, blob_id: 85},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 58, blob_id: 86},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 59, blob_id: 87},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 60, blob_id: 88},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 61, blob_id: 89},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 62, blob_id: 90},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 63, blob_id: 91},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 64, blob_id: 92},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 65, blob_id: 93},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 66, blob_id: 94},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 67, blob_id: 95},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 68, blob_id: 96},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 69, blob_id: 97},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 70, blob_id: 98},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 71, blob_id: 99},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 72, blob_id: 100},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 73, blob_id: 101},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 74, blob_id: 102},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 75, blob_id: 103},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 76, blob_id: 104},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 77, blob_id: 105},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 78, blob_id: 106},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 79, blob_id: 107},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 80, blob_id: 108},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 81, blob_id: 109},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 82, blob_id: 110},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 83, blob_id: 111},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 84, blob_id: 112},
  {name: "image", record_type: "Event", record_id: 1, blob_id: 173},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 130, blob_id: 174},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 131, blob_id: 175},
  {name: "image", record_type: "Event", record_id: 2, blob_id: 176},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 132, blob_id: 177},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 133, blob_id: 178},
  {name: "image", record_type: "Event", record_id: 3, blob_id: 179},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 134, blob_id: 180},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 135, blob_id: 181},
  {name: "image", record_type: "Event", record_id: 4, blob_id: 182},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 136, blob_id: 183},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 137, blob_id: 184},
  {name: "image", record_type: "Event", record_id: 5, blob_id: 185},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 138, blob_id: 186},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 139, blob_id: 187},
  {name: "image", record_type: "Event", record_id: 6, blob_id: 188},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 140, blob_id: 189},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 141, blob_id: 190},
  {name: "image", record_type: "Event", record_id: 7, blob_id: 191},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 142, blob_id: 192},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 143, blob_id: 193},
  {name: "image", record_type: "Event", record_id: 8, blob_id: 194},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 144, blob_id: 195},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 145, blob_id: 196},
  {name: "image", record_type: "Event", record_id: 10, blob_id: 197},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 146, blob_id: 198},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 147, blob_id: 199},
  {name: "image", record_type: "Event", record_id: 11, blob_id: 200},
  {name: "image", record_type: "ActiveStorage::VariantRecord", record_id: 148, blob_id: 201}
])
Spot.create!([
  {name: "道後温泉本館", address: "愛媛県松山市道後湯之町５−６", content: "3000年もの歴史がある日本最古級の温泉で、趣のある木造の本館は、建物全体が国の重要文化財。", city: "2", latitude: nil, longitude: nil, category: "観光地", url: "https://dogo.jp/"},
  {name: "今治市", address: "愛媛県今治市", content: "今治市は、愛媛県北東部に位置する市で、サイクリングやタオル、造船で有名。", city: "1", latitude: 34.0658182, longitude: 132.9976758, category: "観光地", url: "https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjs-eGu3YqAAxUPh1YBHUUGDmoQFnoECA4QAQ&url=https%3A%2F%2Fwww.city.imabari.ehime.jp%2F&usg=AOvVaw3Or5JqX4cFJMs3ZISZ-_xt&opi=89978449"},
  {name: "旧別子銅山東平地区", address: "愛媛県新居浜市立川町６５４", content: "東洋のマチュピチュと称される産業遺産群が有名。", city: "1", latitude: nil, longitude: nil, category: "観光地", url: "https://besshi.com/sangyoisan/tonaru/"},
  {name: "石鎚山", address: "愛媛県上浮穴郡久万高原町若山", content: "登ると山頂に神社があり、広大な景色を一望できる。西日本最高峰の山。", city: "1", latitude: 33.704691, longitude: 133.098526, category: "観光地", url: "https://ishizuchisankei.com/spot/spot01/"},
  {name: "青島", address: "愛媛県大洲市長浜町青島", content: "猫の楽園と呼ばれる、猫好きにはたまらないスポット。", city: "2", latitude: 33.7363564, longitude: 132.4867406, category: "観光地", url: "https://www.city.ozu.ehime.jp/soshiki/nagahamash/0375.html"},
  {name: "下灘駅", address: "愛媛県伊予市双海町大久保", content: "写真から人気が出た駅。写真映えスポット、映画の舞台として有名。", city: "2", latitude: 33.656058, longitude: 132.61012, category: "観光地", url: "https://www.city.iyo.lg.jp/machizukuri/kanko/guidemap/jrshimonada.html"},
  {name: "内子町", address: "愛媛県喜多郡内子町内子", content: "愛媛県の南予地方に位置し、江戸や明治の面影を残す町家や屋敷が建ち並ぶ八日市・護国地区が有名。", city: "3", latitude: 33.5492205, longitude: 132.64621, category: "観光地", url: "https://www.we-love-uchiko.jp/stay-cat/kominka/"},
  {name: "佐田岬半島", address: "愛媛県西宇和郡伊方町", content: "四国の最西端に位置する日本一細長い半島。", city: "3", latitude: 33.4896014, longitude: 132.3560996, category: "観光地", url: "https://www.sadamisaki.com/"},
  {name: "フォレストアドベンチャー・西条", address: "愛媛県西条市河之内486ｰ1 本谷公園内", content: "全国にある自然の中で遊べる体験型フォレストアドベンチャー。", city: "1", latitude: nil, longitude: nil, category: "レジャー", url: "https://foret-aventure.jp/"},
  {name: "とべもりジップライン", address: "愛媛県伊予郡砥部町宮内", content: "全長730ｍの四国最大級のスケールのジップライン。こどもの城・とべ動物園を往復できるコースとなっている。", city: "2", latitude: 33.751182, longitude: 132.795067, category: "レジャー", url: "http://www.i-kodomo.jp/zipline/"},
  {name: "みきゃん型熱気球の係留搭乗体験", address: "愛媛県上浮穴郡久万高原町上野尻", content: "四国唯一の係留熱気球体験、開催期間が限られており、要予約。", city: "2", latitude: 33.646689, longitude: 132.89826, category: "レジャー", url: "https://www.asoview.com/item/activity/pln3000037898/"},
  {name: "面河渓", address: "愛媛県上浮穴郡久万高原町若山", content: "エメラルドグリーンに輝く水、仁淀ブルーで有名な仁淀川の最上流部。", city: "2", latitude: 33.704691, longitude: 133.098526, category: "レジャー", url: "https://goodriver.jp/omogo"},
  {name: "四国カルスト", address: "愛媛県上浮穴郡久万高原町西谷", content: "尾根沿いを行くドライブルート。風車、レストラン、遊歩道があり、自然の絶景を楽しめる。", city: "2", latitude: 33.519229, longitude: 132.946971, category: "レジャー", url: "https://kuma-kanko.com/spot/spot398/"},
  {name: "滑床渓谷", address: "愛媛県宇和島市野川", content: "自然豊かな渓谷。キャニオニング、キャンプなどで遊べる。　", city: "3", latitude: 33.205626, longitude: 132.608566, category: "レジャー", url: "https://sotoasobi.net/activity/canyoning-showerclimbing/9/38/66/1627/8164"},
  {name: "西海観光船", address: "愛媛県南宇和郡愛南町船越１５９９", content: "船底に窓があって海底を見られる遊覧船。ダイビングや、海底を散歩するシーウォーカーも楽しめる。", city: "3", latitude: nil, longitude: nil, category: "レジャー", url: "https://nishiumi.info/"},
  {name: "道の駅 霧の森", address: "愛媛県四国中央市新宮町馬立４４９１−１", content: "新宮村の名産品である新宮茶を使った銘菓「霧の森大福」で有名な道の駅。中にクリームが入った大福。", city: "1", latitude: nil, longitude: nil, category: "グルメ", url: "https://www.kirinomori.co.jp/"},
  {name: "平家谷そうめん流し", address: "愛媛県八幡浜市保内町宮内８−２６４−２", content: "山の中で素麺流しと釣り堀が楽しめるスポット。夏におすすめ。", city: "3", latitude: nil, longitude: nil, category: "グルメ", url: "https://www.city.yawatahama.ehime.jp/doc/2022060100030/"},
  {name: "宇和島　鯛めし", address: "宇和島鯛めし", content: "宇和島近海で採れた真鯛の刺身をタレ、卵黄と混ぜ合わせ、熱々のご飯にのせて食べる郷土料理。", city: "3", latitude: 33.8432178, longitude: 132.7709609, category: "グルメ", url: "https://www.taimeshi.jp/"},
  {name: "大山祇神社", address: "愛媛県今治市大三島町宮浦３３２７", content: "古代のクスノキに囲まれた国指定重要文化財の神社。国宝の武具が所蔵されている。", city: "1", latitude: nil, longitude: nil, category: "歴史", url: "https://oomishimagu.jp"},
  {name: "村上海賊ミュージアム", address: "愛媛県今治市宮窪町宮窪１２８５ 内", content: "瀬戸内海で活躍した能島村上水軍の歴史を紹介する博物館。", city: "1", latitude: nil, longitude: nil, category: "歴史", url: "https://www.city.imabari.ehime.jp/museum/suigun/"},
  {name: "松山城", address: "愛媛県松山市丸之内１", content: "松山城は、松山市の中心部にある広大な平山城であり、ロープウェーなどで移動できます。", city: "2", latitude: nil, longitude: nil, category: "歴史", url: "https://www.matsuyamajo.jp"},
  {name: "高昌寺", address: "愛媛県喜多郡内子町城廻１１７", content: "大きな涅槃の石像で有名な内子のお寺。", city: "3", latitude: nil, longitude: nil, category: "歴史", url: ""},
  {name: "臥龍山荘", address: "愛媛県大洲市大洲４１１−２", content: "景勝地として知られる清流肱川湖畔にある山荘。国の重要文化財に指定される3つの数寄屋建築や日本庭園がある。", city: "3", latitude: nil, longitude: nil, category: "歴史", url: "https://www.garyusanso.jp/"},
  {name: "宇和文化の里 開明学校", address: "愛媛県西予市宇和町卯之町３丁目１１０", content: "日本の明治時代の学校教育の風景が感じられる建物。明治の授業体験を受けられます。", city: "3", latitude: nil, longitude: nil, category: "歴史", url: "https://www.city.seiyo.ehime.jp/miryoku/uwachonomachinami/kaimei/index.html"},
  {name: "宇和島市営闘牛場", address: "愛媛県宇和島市和霊町１丁目４９６−２", content: "年に4回開かれる、うわじま闘牛定期大会が有名。", city: "3", latitude: nil, longitude: nil, category: "歴史", url: "https://www.tougyu.com"},
  {name: "宇和島城", address: "愛媛県宇和島市丸之内", content: "1596 年頃に丘の上に建てられた城。現在は 3 階建ての天守のみが残っており、見学が可能。", city: "3", latitude: nil, longitude: nil, category: "歴史", url: "https://www.city.uwajima.ehime.jp/site/uwajima-jo/"},
  {name: "今治タオル 本店", address: "愛媛県今治市東門町５丁目１４−３　", content: "タオル産業の発展を担ってきた柔らかく品質の高い、全国的にも有名な今治タオル。", city: "1", latitude: nil, longitude: nil, category: "お土産", url: "https://www.imabaritowel.jp"},
  {name: "ポンジュース発祥の地", address: "愛媛県松山市中須賀３丁目１１", content: "愛媛県のみかん産業をどのように発展させるかと言う思いから生まれたポンジュース。愛媛のみかんジュースといえばこれ。", city: "2", latitude: nil, longitude: nil, category: "お土産", url: "http://www.ehime-inryo.co.jp"},
  {name: "砥部焼陶芸館", address: "愛媛県伊予郡砥部町宮内８３", content: "砥部焼は、愛媛県の砥部町を中心に作られている陶磁器。愛媛県指定無形文化財。", city: "2", latitude: nil, longitude: nil, category: "お土産", url: "https://www.togeikan.com/index.php"}
])
Event.create!([
  {content: "市民パレード・大名武者行列、その他イベントが開催される春の大規模なお祭り。", name: "松山お城祭り", address: "松山城", season: "春", image: nil, date: "4月上旬頃"},
  {content: "砥部焼の窯元の作品10万点が一堂に集まる「砥部焼まつり」。毎年県内外からの多くの来場者で賑わいます。", name: "砥部焼まつり", address: "愛媛県伊予郡砥部町千足400番地", season: "春", image: nil, date: "4月中旬"},
  {content: "翠波高原の緩やかな傾斜地一面を菜の花が黄色に染め、当日はイベントが催されるため、家族連れなど行楽客で賑わいます。", name: "翠波高原 菜の花まつり", address: "四国中央市金砂町平野山乙306-1翠波高原", season: "春", image: nil, date: "4月中旬ごろ"},
  {content: "２日間にわたって伝統的な踊りや屋台、花火が楽しめる今治市の夏祭り。", name: "おんまく", address: "今治港", season: "夏", image: nil, date: "8月初旬"},
  {content: "「牛鬼（うしおに）」とは全長5～6メートルの山車のこと。牛鬼が市内を練り歩く迫力のパレードや伝統の宇和島おどり、夜空と宇和海を彩る花火大会などで盛り上がります。", name: "うわじま牛鬼まつり", address: "宇和島市内", season: "夏", image: nil, date: "7月下旬"},
  {content: "大洲の夏から秋にかけての風物詩。", name: "大洲のうかい", address: "肱川", season: "夏", image: nil, date: "6月〜9月"},
  {content: "愛媛を代表する秋祭である。複数の太鼓台が集まって行なわれるかきくらべが有名。", name: "新居浜太鼓まつり", address: "新居浜", season: "秋", image: nil, date: "10月中旬"},
  {content: "喧嘩神輿と呼ばれる。神輿と神輿がぶつかり合い、神輿を押し合う様は圧巻。", name: "松山道後秋祭り", address: "愛媛県松山市伊予鉄道後温泉駅前", season: "秋", image: nil, date: "10月初旬"},
  {content: "菊間町加茂神社の祭事として行われる「お供馬の走り込み」は、愛媛県無形民俗文化財の指定を受けた伝統行事。", name: "菊間祭り", address: "菊間町加茂神社", season: "秋", image: nil, date: "10月中旬"},
  {content: "大洲城をバックに、澄んだ冬空に花火が打ちあがる。", name: "大洲川まつり花火大会　冬の陣", address: "肱川肱北河原", season: "冬", image: nil, date: "1月初旬"},
  {content: "四国最大規模の日本庭園内には四季折々の花々が咲き乱れ160本の梅の花見が楽しめます。", name: "南楽園梅まつり", address: "南楽園", season: "冬", image: nil, date: "1月〜3月"},
  {content: "伊豫豆比古命神社で毎年旧暦正月8日を例祭日として前後3日間開催されるのが、愛媛県で冬を代表する催しとして有名。毎年屋台がずらりと並ぶ。", name: "椿まつり", address: "椿神社", season: "冬", image: nil, date: "1月下旬"}
])
User.create!([
  {email: "dummy1@example.com", encrypted_password: "$2a$12$dbquWx9dBGNvN0tN..wnse2AeB57nUEp7RJfXIW.ZnxevUjtwvVJO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil}
])
